### ISSUE TITLE
user signup

### ISSUE THREAD

**Issue by gkiko** [freeuni-sdp/xo-signin#10]
მომხმარებელს ეგზავნება წერილი ლინკით მისი პროფილის გასააქტიურებლად?
დავიწყებული პაროლი ეგზავნბე მითითებულ მეილზე?

**Comment by gati3478** [comment]
ჰო, მომხმარებელს ეგზავნება წერილი ლინკით (ლინკზე უბრალოდ გასააქტიურებელი ტოკენია) და კი პაროლი ეგზავნება მეილზე. თავდაპირველად იმეილიდან ახალი პაროლის დაყენების API მეწერა, მაგრამ ახლა გავამარტივე და მეილზე პირდაპირ პაროლი იგზავნება.
