### ISSUE TITLE
/recover_password POST

### ISSUE THREAD

**Issue by gkiko** [freeuni-sdp/xo-signin#11]
_GET_ შესაცვლელია _POST_-ად წესის მიხედვით. [read](http://stackoverflow.com/a/983458/660408)

ესეთი მახინჯი მოთხოვნები იგზავნება

``` http
http://private-6e6f0-xosignin.apiary-mock.com/recover_password?{%22email%22:%22a@a%22}
```

**Comment by gati3478** [comment]
მართალია, what a shame. შევასწორე.
