### ISSUE TITLE
can't confirm email

### ISSUE THREAD

**Issue by gkiko** [freeuni-sdp/xo-signin#19]
ამას მიწერს მეილზე მოსულ ლინკზე რომ დაგავდივარ
`Cannot GET /confirm_account?token=b7a4bd21e78d05ddbf1d87753c58d49bf9eca51c&username=gkiko&email=gkiko10@freeuni.edu.ge`

**Comment by gati3478** [comment]
აჰა, მართალია. ეგ ლინკი რეალურად არ ააქტიურებს, ვიფიქრე რომ მაგ პეიჯიდან (ლინკს რაზეც გადაყავხარ) იქნებოდა confirm-ზე მოთხოვნის გაგზავნა სერვისისთვის არა თვითნ ლინკზე დაჭერით, მაშინ შევცვლი ისე რომ ლინკზე დაჭერით მოხდეს პირდაპირ გააქტიურება.

**Comment by gkiko** [comment]
apiary-ზე გიწერია, რომ GET -ს გზავნი მეილის დადასტურებისას, რომელსაც ტანს ატან. http://stackoverflow.com/a/983458/660408

**Comment by gati3478** [comment]
შევცვალე ისე რომ მეილიდან ლინკზე დაჭერით ანგარიში დამოწმებულად ჩაითვალოს. კარგად ვერ მივხვდი + რამე უნდა დავაბრუნო უკან?

**Comment by gkiko** [comment]
GET-ს ტანი არ უნდა გაატანო.

**Comment by gati3478** [comment]
იმეილის ლინკი შევცვალე http://xo-signin.herokuapp.com/confirm_email/b7a4bd21e78d05ddbf1d87753c58d49bf9eca51c -ით შენი ანგარიშის ამოცნობა მოხდება. GET-ს ტანს არ ვატან ახლა, მარტო ტოკენი მიდის.

**Comment by gati3478** [comment]
დარეგისტირებული და შემდგომ აქტივირებული ინფორმაციით დალოგინება უკვე შეგიძლია, თეიბლები გავასუფთავე და შეგიძლია ახლიდან გაიარო რეგისტრაცია.
