### ISSUE TITLE
Create API doc on ApiAry (API Blueprint), write down result link on Architecture page

### ISSUE THREAD

**Issue by gati3478** [freeuni-sdp/xo-signin#3]

**Comment by gati3478** [comment]
Done, [commit](https://github.com/freeuni-sdp/xo-signin/commit/250e1f1bc270c9b6ea497207b2255f1061fdcdff)

**Comment by gmamaladze** [comment]
API documentation still missing: http://docs.xosignin.apiary.io/#

![image](https://cloud.githubusercontent.com/assets/1906405/7996539/a0d765b4-0b21-11e5-801c-bfdca7f719e6.png)

**Comment by gmamaladze** [comment]
@gati3478 @MT13

**Comment by gati3478** [comment]
გავასწორე, apiary.abid ფაილი docs.xosignin.apiary.io-ზე არის უკვე.

**Comment by gati3478** [comment]
გავაუმჯობესეთ API: password recovery-სა და username recovery-ის შესაბამისი URL მივეცით, ასევე e-mail-ის დადასტურებისა და e-mail-დან პაროლის აღდგენის ინტერფეისიც დავამატეთ.
[Commit](https://github.com/freeuni-sdp/xo-signin/commit/b345e4179ed343ef3dde08214ee9fa62994bb0bf)
